# Generated by Django 4.0.4 on 2022-05-29 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.CharField(default='I am cool', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(default='Shashank', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='media/default.png', null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(default='Software Engineer', max_length=200, null=True),
        ),
    ]
