# Generated by Django 4.0.2 on 2022-06-02 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0003_alter_profile_desc_alter_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_url',
            field=models.URLField(default='http://127.0.0.1:8000/get/ppp/<django.db.models.fields.related.OneToOneField>'),
        ),
    ]
