# Generated by Django 4.0.2 on 2022-06-05 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profileapp', '0008_alter_profile_profile_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(choices=[('B.Sc', 'Bachelor of Science'), ('B.tech', 'Bachelor of Technology'), ('M.Sc', 'Masters of Science')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_id', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
