# Generated by Django 4.0.2 on 2022-06-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0009_education'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='course_id',
            new_name='user_name',
        ),
    ]
