# Generated by Django 4.0.2 on 2022-06-05 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0010_rename_course_id_education_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='course',
            field=models.CharField(choices=[('*', 'Select Course'), ('B.Sc', 'Bachelor of Science'), ('B.tech', 'Bachelor of Technology'), ('M.Sc', 'Masters of Science')], max_length=15),
        ),
    ]
