# Generated by Django 4.0.2 on 2022-06-06 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0011_alter_education_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='course',
            new_name='graduation',
        ),
        migrations.RemoveField(
            model_name='education',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='education',
            name='start_date',
        ),
        migrations.AddField(
            model_name='education',
            name='End_date_10th',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='End_date_12th',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Start_date_10th',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='Start_date_12th',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='class_10th',
            field=models.CharField(choices=[('*', 'Select Board'), ('cbase', 'CBSE'), ('up', 'U.P.'), ('icse', 'ICSE'), ('Biahr', 'Bihar Board')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='class_10th_School',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='class_12th',
            field=models.CharField(choices=[('*', 'Select Board'), ('cbase', 'CBSE'), ('up', 'U.P.'), ('icse', 'ICSE'), ('Biahr', 'Bihar Board')], max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='class_12th_School',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='graduation_end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='graduation_percentage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='graduation_start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='percentage_10th',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='percentage_12th',
            field=models.FloatField(null=True),
        ),
    ]
