# Generated by Django 4.0.2 on 2022-03-21 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialPython_app', '0002_alter_usermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(default='SOME STRING', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='email',
            field=models.EmailField(max_length=60),
        ),
        migrations.CreateModel(
            name='userProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=15)),
                ('job', models.CharField(max_length=35)),
                ('education', models.CharField(max_length=30)),
                ('work_experience', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=60)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socialPython_app.usermodel')),
            ],
        ),
    ]
