# Generated by Django 4.0.2 on 2022-03-21 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialPython_app', '0003_usermodel_user_name_alter_usermodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='socialPython_app.usermodel'),
        ),
    ]
