# Generated by Django 4.0.2 on 2022-03-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialPython_app', '0004_alter_userprofilemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofilemodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
