# Generated by Django 4.0.2 on 2022-03-24 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialPython_app', '0005_remove_userprofilemodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofilemodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='relation', to='socialPython_app.usermodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
    ]
